zuul:
    routes:
        book:
            path: /enterprise-resources/public/customer/**
            url: http://195.233.190.232:8002/enterprise-resources/public/customer/
        book1:
            path: /enterprise-resources/public/identity/**
            url: http://195.233.190.232:8002/enterprise-resources/public/identity/
        book2:
            path: /enterprise-resources/public/order/**
            url: http://195.233.190.232:8002/enterprise-resources/public/order/
        book3:
            path: /enterprise-resources/public/service/**
            url: http://195.233.190.232:8002/enterprise-resources/public/service/
        book4:
            path: /enterprise-resources/public/product/**
            url: http://195.233.190.232:8002/enterprise-resources/public/product/
        book5:
            path: /enterprise-resources/public/subscription/**
            url: http://195.233.190.232:8002/enterprise-resources/public/subscription/
        book6:
            path: /enterprise-resources/public/technical/**
            url: http://195.233.190.232:8002/enterprise-resources/public/technical/
        book7:
            path: /enterprise-resources/public/payment/**
            url: http://195.233.190.232:8002/enterprise-resources/public/payment/
server:
    port: 443
#    ssl:  
#      key-store: classpath:api-mobile-vfal.jks
#      key-store-password: 4p1zuul2017vF4L
#      key-password: "[m0bB01p$].t3st1"
      
ribbon:
    eureka:
        enabled: false
